#!/bin/csh
# this script creates a pid file for running coral processes
# this script can only be run by coral user

# create pid directory
setenv PIDDIR ~/pids
mkdir -p $PIDDIR

# check coral user ID 
setenv CORALUID `id -u coral`
echo "Coral UID: $CORALUID"

# list out the coral processes that are active and running
setenv PROCESSES `ap | grep coral | awk '{print $2}'| sed -r "s/\x1B\[([0-9]{1,3}(;[0-9]{1,2})?)?[mGK]//g"`
echo "Current processes: $PROCESSES"

# loop through the processes and create a pid file for each of them
foreach p ($PROCESSES)
  echo "$p"
  pgrep -f "$p" -U "$CORALUID" > $PIDDIR/"$p".pid
end
